// webpack.mix.js

let mix = require('laravel-mix');

mix
.sass('src/sass/global.sass', 'styles/')
.js('src/scripts/global.js', 'js/')
.js('src/scripts/resources/site-hero.js', 'js/')
.sass('src/sass/pages/homepage.sass', 'styles/')
.sass('src/sass/pages/newdevelopments.sass', 'styles/')
.js('src/scripts/pages/newdevelopments.js', 'js/')
.sass('src/sass/pages/single-newdevelopments.sass', 'styles/')
.js('src/scripts/pages/single-newdevelopments.js', 'js/')
.sass('src/sass/pages/neighborhoods.sass', 'styles/')
.js('src/scripts/pages/neighborhoods.js', 'js/')
.sass('src/sass/pages/blog.sass', 'styles/')
.sass('src/sass/pages/single-blog.sass', 'styles/')
.js('src/scripts/pages/blog.js', 'js/')
.js('src/scripts/pages/single-blog.js', 'js/')
.sass('src/sass/pages/archive.sass', 'styles/')
.js('src/scripts/pages/homepage.js', 'js/')
.sass('src/sass/pages/about.sass', 'styles/')
.js('src/scripts/pages/about.js', 'js/')
.sass('src/sass/pages/single-listings.sass', 'styles/')
.js('src/scripts/pages/single-listings.js', 'js/')
.sass('src/sass/pages/thankyou.sass', 'styles/')
.js('src/scripts/pages/thankyou.js', 'js/')
.sass('src/sass/pages/sell.sass', 'styles/')
.js('src/scripts/pages/sell.js', 'js/')
.sass('src/sass/pages/buy.sass', 'styles/')
.js('src/scripts/pages/buy.js', 'js/')
.sass('src/sass/pages/single-neighborhoods.sass', 'styles/')
.js('src/scripts/pages/single-neighborhoods.js', 'js/')
.sass('src/sass/pages/contact.sass', 'styles/')
.sass('src/sass/pages/talks.sass', 'styles/')
.js('src/scripts/pages/talks.js', 'js/')
.sass('src/sass/pages/coaching.sass', 'styles/')
.js('src/scripts/pages/coaching.js', 'js/')